# Site settings
title: Phootwork Library
description: > # this means to ignore newlines until "baseurl:"
  The phootwork php library fills gaps in the php language and provides
  better solutions than the existing ones php offers.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
excludes: ['README.md']
github_username: phootwork

# Build settings
markdown: kramdown
#highlighter: pygments

collections:
  lang:
    output: true
    title: "Lang"
    description: "Missing PHP language constructs"
    nav:
      - title: "Overview"
        path: ""
      - title: "Installation"
        path: "installation"
      - title: "Usage"
      - title: "Array"
        path: "array"
      - title: "String"
        path: "string"
      - title: "Comparison"
        path: "comparison"
  collection:
    output: true
    title: "Collection"
    description: "PHP Collections library (List, Set, Map, Queue & Stack)"
    nav:
      - title: "Overview"
        path: ""
      - title: "Installation"
        path: "installation"
      - title: "Usage"
      - title: "Collections"
        path: "collections"
      - title: "Searching"
        path: "searching"
      - title: "Sorting"
        path: "sorting"
      - title: "Goodies"
        path: "goodies"
  json:
    output: true
    title: "Json"
    description: "PHP Json library"
    nav:
      - title: "Overview"
        path: ""
      - title: "Installation"
        path: "installation"
      - title: "Usage"
      - title: "Encode"
        path: "encode"
      - title: "Decode"
        path: "decode"
      - title: "Error Handling"
        path: "error-handling"
  file:
    output: true
    title: "File"
    description: "PHP File library for the local filesystem"
    nav:
      - title: "Overview"
        path: ""
      - title: "Installation"
        path: "installation"
      - title: "Usage"
      - title: "Paths"
        path: "paths"
      - title: "Filesystem"
        path: "filesystem"
      - title: "Files"
        path: "files"
      - title: "Directories"
        path: "directories"
      - title: "Testing"
        path: "testing"
