site_name: Phootwork
repo_url: https://github.com/phootwork/phootwork.github.io/
edit_uri: "docs/"
theme: cinder
copyright: "Phootwork is licensed under the <a href='https://github.com/phootwork/phootwork/blob/master/LICENSE'>MIT license</a>"
markdown_extensions:
  - admonition
  - fontawesome_markdown
nav:
  - Home: index.md
  - Libraries:
      - Collection: collection.md
      - File: file.md
      - Json: json.md
      - Lang: lang.md
      - Tokenizer: tokenizer.md
      - Xml: xml.md
  - Api: https://phootwork.github.io/api
  - About:
      - About us: about.md
      - Contributing: contributing.md
      - Documentation Contributing: docs_contributing.md
      - License: license.md
