site_name: Phootwork
site_url: https://phootwork.github.io
site_author: Thomas Gossmann, Cristiano Cinotti
site_description: "Phootwork is a collection of php libraries which fill gaps in the php language and provides consistent object oriented solutions"
repo_url: https://github.com/phootwork/phootwork.github.io/
edit_uri: "docs/"
theme:
  name: cinder
  highlightjs: true
copyright: "Phootwork is licensed under the <a href='https://github.com/phootwork/phootwork/blob/master/LICENSE'>MIT license</a>"
markdown_extensions:
  - admonition
  - fontawesome_markdown
nav:
  - Home: index.md
  - Libraries:
      - Collection: collection.md
      - File: file.md
      - Json: json.md
      - Lang: lang.md
      - Tokenizer: tokenizer.md
      - Xml: xml.md
  - Api: https://phootwork.github.io/api
  - About:
      - About us: about.md
      - Contributing: contributing.md
      - Documentation Contributing: docs_contributing.md
      - License: license.md
